spring:
  datasource:
    name: popquiz
    url: jdbc:mysql://localhost:3306/popquiz
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB

mybatis:
  #映射文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

server:
  tomcat:
    uri-encoding: UTF-8
    relaxed-path-chars: "<,>,[,],\\,^,`,{,|,}"
    relaxed-query-chars: "<,>,[,],\\,^,`,{,|,}"

